/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

# schema
CREATE SCHEMA IF NOT EXISTS `restful_api` DEFAULT CHARACTER SET latin1 ;
USE `restful_api` ;

# table user_token
# ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS  `restful_api`.`user_token` (
  `token_id` int(70) NOT NULL AUTO_INCREMENT,
  `user_id_fk` int(70) NOT NULL,
  `token` varchar(600) DEFAULT NULL,
  PRIMARY KEY (`token_id`),
  UNIQUE KEY `user_id_fk_UNIQUE` (`user_id_fk`),
  CONSTRAINT `user_info_foreign_key` FOREIGN KEY (`user_id_fk`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `user_token` WRITE;
/*!40000 ALTER TABLE `user_token` DISABLE KEYS */;

INSERT INTO `user_token` (`token_id`, `user_id_fk`, `token`, `expires_at`)
VALUES
  (1,1,'295ba2925a7015ff5726ca57e5560c0bac85c77081ce8ff954b14122014cb533fb9dde7fbaf1b77b2f675a8fe287bf719ad57b5d22905b6afd76986410bd31da1cc876','2205-01-01 22:05:01');

/*!40000 ALTER TABLE `user_token` ENABLE KEYS */;
UNLOCK TABLES;

DELIMITER ;;
/*!50003 SET SESSION SQL_MODE="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION" */;;
/*!50003 CREATE */ /*!50003 TRIGGER `default_expire_date` BEFORE INSERT ON `user_token` FOR EACH ROW set new.expires_at=DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 7 DAY) */;;
/*!50003 SET SESSION SQL_MODE="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION" */;;
/*!50003 CREATE */ /*!50003 TRIGGER `update_expire_date` BEFORE UPDATE ON `user_token` FOR EACH ROW set new.expires_at=DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 7 DAY) */;;
DELIMITER ;
/*!50003 SET SESSION SQL_MODE=@OLD_SQL_MODE */;

# table user
# ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS  `restful_api`.`user` (
  `user_id` int(70) NOT NULL AUTO_INCREMENT,
  `email` varchar(150) NOT NULL DEFAULT '',
  `password` varchar(65) DEFAULT NULL,
  `join_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_email_UNIQUE` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `user` WRITE;
/*!40000 ALTER TABLE `user` DISABLE KEYS */;

INSERT INTO `user` (`user_id`, `email`, `password`, `join_date`, `status`)
VALUES
	(1,'jeremy@example.com','$2a$12$6HK7GZXHhI27.sScLG4HzOhSvneo6xzHHYC//9RTrox0.yJbQ7SXK','2000-01-01 00:00:01','active'),
	(2,'jb@example.com','$2a$12$59K9srxaF2hA6KJIbR6D9OstdLEiizw1Xvn6rIoY4lIC8cDK9ZmwK','2017-05-29 22:02:15',NULL);

/*!40000 ALTER TABLE `user` ENABLE KEYS */;
UNLOCK TABLES;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
